# Overview

This notebook id dedicated for evaluating NER model on a benchmark dataset.

# Step 0 - Setup
Run the code below to mount your Google Drive and most of the necessary packages to carry out the evaluation

**Action:**
No code changes required. When prompted, connect your Google account

In [1]:
%%capture
!cd /content/
!rm -rf ./CASM_utils/
!pip install git+https://github.com/ay94/multilingual-ner.git!pip install -e CASM_utils/
!cd /content/CASM_utils


import CASM_utils
import importlib
from CASM_utils import utils
importlib.reload(utils)

In [2]:
## Mount GDrive
from google.colab import drive
drive.mount('/content/drive/', force_remount=True)

## Imports
import os
import numpy as np
import pandas as pd
from pathlib import Path
from tqdm.notebook import tqdm
from collections import Counter, defaultdict

Mounted at /content/drive/

In [15]:
# direct the file handler to the data folder
FOLDER = '/content/drive/MyDrive/CASM/FAST/German/NER/Benchmark'
fh = utils.FileHandler(FOLDER)

 # Read results
 - Read corss model results
 - Read corss datasets results
 -

wikineural

In [16]:
def extract_results():
  TAGs = ['LOC', 'PER', 'ORG']
  for TAG in TAGs:
    entity_results = []
    directory = Path(fh.cr_fn('outputs'))
    for subdir, dirs, files in os.walk(directory):
        for file in files:
            # Construct the file's full path
            file_path = os.path.join(subdir, file)
            excluded_folder = file_path.split('/')[-2]
            if excluded_folder != 'wikiann-span':
              # Open and read the file
              file_name = file_path.split('/')[-1]
              model_name = file_path.split('/')[-2]
              if 'seqeval' in file_name:
                df = pd.read_csv(file_path)
                df['Model Name'] = model_name
                df['Data Name'] = file_name.split('-')[0]
                print()
                display(df[df['Tag'] == TAG])
                entity_results.append(df[df['Tag'] == TAG])
    pd.concat(entity_results).to_csv(
        fh.cr_fn(f'outputs/consolidated-{TAG}.csv'),
        index=False
    )

In [17]:
extract_results()

   Tag  Precision  Recall      F1  support               Model Name Data Name
0  LOC     0.6025  0.7031  0.6489     4961  fhswf-bert-GermEval2014    xtreme

,Tag,Precision,Recall,F1,support,Model Name,Data Name
0,LOC,0.8651,0.899,0.8817,2376,fhswf-bert-GermEval2014,germeval_14

   Tag  Precision  Recall      F1  support          Model Name Data Name
0  LOC     0.8662  0.8909  0.8784     4961  gunghio-xlm-xtreme    xtreme

   Tag  Precision  Recall      F1  support          Model Name    Data Name
0  LOC     0.6841  0.6263  0.6539     2376  gunghio-xlm-xtreme  germeval_14

   Tag  Precision  Recall      F1  support              Model Name Data Name
0  LOC     0.8723  0.8869  0.8796     4961  julian-roberta-Wikiann    xtreme

   Tag  Precision  Recall     F1  support              Model Name    Data Name
0  LOC     0.7524  0.6355  0.689     2376  julian-roberta-Wikiann  germeval_14

   Tag  Precision  Recall      F1  support               Model Name Data Name
2  PER     0.7633  0.7408  0.7519     4750  fhswf-bert-GermEval2014    xtreme

,Tag,Precision,Recall,F1,support,Model Name,Data Name
2,PER,0.8978,0.917,0.9073,1639,fhswf-bert-GermEval2014,germeval_14

   Tag  Precision  Recall      F1  support          Model Name Data Name
2  PER     0.9333  0.9194  0.9263     4750  gunghio-xlm-xtreme    xtreme

   Tag  Precision  Recall      F1  support          Model Name    Data Name
2  PER     0.7553  0.7383  0.7467     1639  gunghio-xlm-xtreme  germeval_14

   Tag  Precision  Recall      F1  support              Model Name Data Name
2  PER     0.9322  0.9206  0.9264     4750  julian-roberta-Wikiann    xtreme

,Tag,Precision,Recall,F1,support,Model Name,Data Name
2,PER,0.8478,0.7102,0.7729,1639,julian-roberta-Wikiann,germeval_14

   Tag  Precision  Recall     F1  support               Model Name Data Name
1  ORG      0.627  0.3558  0.454     4157  fhswf-bert-GermEval2014    xtreme

,Tag,Precision,Recall,F1,support,Model Name,Data Name
1,ORG,0.7642,0.7466,0.7553,1385,fhswf-bert-GermEval2014,germeval_14

   Tag  Precision  Recall      F1  support          Model Name Data Name
1  ORG     0.8064  0.8114  0.8089     4157  gunghio-xlm-xtreme    xtreme

   Tag  Precision  Recall      F1  support          Model Name    Data Name
1  ORG     0.2228  0.6383  0.3303     1385  gunghio-xlm-xtreme  germeval_14

   Tag  Precision  Recall      F1  support              Model Name Data Name
1  ORG     0.8085  0.8268  0.8176     4157  julian-roberta-Wikiann    xtreme

,Tag,Precision,Recall,F1,support,Model Name,Data Name
1,ORG,0.2096,0.6426,0.3161,1385,julian-roberta-Wikiann,germeval_14

wikiann

In [18]:
LOC = pd.read_csv(
    fh.cr_fn(f'outputs/consolidated-LOC.csv')
)
PER = pd.read_csv(
    fh.cr_fn(f'outputs/consolidated-PER.csv')
)
ORG = pd.read_csv(
    fh.cr_fn(f'outputs/consolidated-ORG.csv')
)

In [24]:
ORG

,Tag,Precision,Recall,F1,support,Model Name,Data Name
0,ORG,0.6270,0.3558,0.4540,4157,fhswf-bert-GermEval2014,xtreme
1,ORG,0.7642,0.7466,0.7553,1385,fhswf-bert-GermEval2014,germeval_14
2,ORG,0.8064,0.8114,0.8089,4157,gunghio-xlm-xtreme,xtreme
3,ORG,0.2228,0.6383,0.3303,1385,gunghio-xlm-xtreme,germeval_14
4,ORG,0.8085,0.8268,0.8176,4157,julian-roberta-Wikiann,xtreme
5,ORG,0.2096,0.6426,0.3161,1385,julian-roberta-Wikiann,germeval_14

In [25]:
f1_loc = LOC.groupby('Model Name')['F1'].mean()
f1_per = PER.groupby('Model Name')['F1'].mean()
f1_org = ORG.groupby('Model Name')['F1'].mean()

results = pd.DataFrame({
    'LOC': f1_loc,
    'PER': f1_per,
    'ORG': f1_org
}).reset_index().rename(columns={'Model Name': 'Model / Data Name'})

In [26]:
results

         Model / Data Name      LOC      PER      ORG
0  fhswf-bert-GermEval2014  0.76530  0.82960  0.60465
1       gunghio-xlm-xtreme  0.76615  0.83650  0.56960
2   julian-roberta-Wikiann  0.78430  0.84965  0.56685

In [27]:
results.to_csv(
    fh.cr_fn(f'outputs/consolidated_average_entity.csv')

)

  Model / Data Name      LOC      PER      ORG
0             mbert  0.81180  0.93730  0.72425
1           roberta  0.79755  0.93485  0.65725
2       xlm-roberta  0.77735  0.90295  0.59995